networks:
  app-network:

x-app-volume:
  &app-volume
  type: bind
  source: ./
  target: /var/www/html
x-app-dir: &app-dir /var/www/html

services:
  app:
    build:
      context: _config/php/
      dockerfile: Dockerfile
      args:
        UID: ${MY_UID}
        GID: ${MY_GID}
    tty: true
    restart: unless-stopped
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal idekey=VSCODE start_with_request=yes discover_client_host=1 log_level=0"
      XDEBUG_MODE: "debug,coverage"
      XDEBUG_TRIGGER: "trigger"
      TZ: "Europe/Athens"
      DEBIAN_FRONTEND: "noninteractive"
    ports:
      - "127.0.0.1:5173:5173"
    volumes:
      - *app-volume
      - ./_config/php/php.ini:/usr/local/etc/php/php.ini
      - ./_config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: *app-dir
    networks:
      - app-network

  caddy:
    image: caddy:2.8.4-alpine
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - *app-volume
      - ./_config/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./_data/caddy/data:/data
      - ./_data/caddy/config:/config
    depends_on:
      - app
      - mariadb
    networks:
      - app-network

  mariadb:
    image: mariadb:11
    restart: unless-stopped
    tty: true
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
    volumes:
      - ./_data/mariadb:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - app-network
